# Generated by Django 3.2.25 on 2025-02-13 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0002_remove_domain_url_in_domain_alter_url_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=20)),
                ('details', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='url',
            name='captured_at',
        ),
        migrations.AlterField(
            model_name='url',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='url', to='llm.domain'),
        ),
        migrations.AlterField(
            model_name='url',
            name='published_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SitemapScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitemap_url', models.URLField(unique=True)),
                ('last_scanned_at', models.DateTimeField(auto_now=True)),
                ('last_modified_header', models.DateTimeField(blank=True, null=True)),
                ('lastmod_from_sitemap', models.DateTimeField(blank=True, null=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='llm.domain')),
            ],
        ),
    ]
